on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install wireviz
      - run: wireviz -o output wiring.yaml
