on: [push]
concurrency:
  group: github-pages
  cancel-in-progress: false
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - uses: ts-graphviz/setup-graphviz@v2
      - run: pip install -r requirements.txt
      - run: wireviz -o output wiring.yaml
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: output
      -  uses: actions/deploy-pages@v2
         id: deployment
         